question_data = [
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Soccer player Cristiano Ronaldo opened a museum dedicated to himself.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Peyton Manning retired after winning Super Bowl XLIX.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Tennis was once known as Racquetball.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The Olympics tennis court is a giant green screen.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Roger Federer is a famous soccer player.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Wilt Chamberlain scored his infamous 100-point-game against the New York Knicks in 1962.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "medium",
        "question": "In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "medium",
        "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "easy",
        "question": "There are a total of 20 races in Formula One 2016 season.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
]
